name: Build Flutter APK

on:
  push:

jobs:
  build:
    name: Build ARM64 APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Cache Flutter SDK
        uses: actions/cache@v3
        with:
          path: /opt/flutter
          key: flutter-sdk-${{ runner.os }}-3.35.4

      - name: Install Flutter (from cache or fresh)
        run: |
          if [ ! -d "/opt/flutter" ]; then
            git clone https://github.com/flutter/flutter.git -b 3.35.4 /opt/flutter
          fi
          echo "/opt/flutter/bin" >> $GITHUB_PATH
          flutter --version

      - name: Cache Android SDK
        uses: actions/cache@v3
        with:
          path: $HOME/android-sdk
          key: android-sdk-${{ runner.os }}

      - name: Set up Android SDK
        run: |
          if [ ! -d "$HOME/android-sdk" ]; then
            mkdir -p $HOME/android-sdk
            yes | sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.2"
          fi
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Install dependencies
        run: flutter pub get

      - name: Build ARM64 APK
        run: flutter build apk --release --target-platform android-arm64

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        name: arm64-release-apk
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
