name: Build Flutter APK

on:
  workflow_dispatch:  # Enables manual triggering from GitHub UI

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          cache: true

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            build
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Install dependencies
        run: flutter pub get

      - name: Build arm64 APK
        run: flutter build apk --release --target-platform android-arm64

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-arm64-apk
          path: build/app/outputs/flutter-apk/app-release.apk
